server {
    listen 80;
    server_name coffeephoenix.ru www.coffeephoenix.ru;

    root /var/www/coffeephoenix/coffee/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
