server {
    listen 80;
    server_name partniers.coffeephoenix.ru;

    root /var/www/coffeephoenix/partniers/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
